core/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('question/', views.QuestionCreateView.as_view(), name="question_create_view"),
    # path('', ),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

core/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Timestamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True


class Question(Timestamp):
    title = models.CharField(max_length=255, verbose_name = _(u"Título"))
    description = models.TextField(verbose_name = _(u"Descrição"), blank=True, null=True)

    class Meta:
        verbose_name = _(u"Questão")
        verbose_name_plural = _(u"Questões")

    def __str__(self):
        return F"#{self.id} - Question"


class Alternative(Timestamp):
    description = models.CharField(max_length=255, verbose_name = _(u"Descrição"))
    is_correct = models.BooleanField(verbose_name = _(u"É a correta?"), default=False)
    question = models.ForeignKey(Question, verbose_name = _(u"Questão"), on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name = _(u"Alternativa")
        verbose_name_plural = _(u"Alternativas")

    def __str__(self):
        return F"#{self.id} - Alternative"

core/forms.py
from django.forms import ModelForm
from core.models import Question, Alternative
from django.forms import inlineformset_factory


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = "__all__"


class AlternativeForm(ModelForm):
    class Meta:
        model = Alternative
        fields=["description", "is_correct"]

AlternativeInlineFormset = inlineformset_factory(
    Question,
    Alternative,
    form=AlternativeForm,
    extra=5,
    # max_num=5,
    # fk_name=None,
    # fields=None, exclude=None, can_order=False,
    # can_delete=True, max_num=None, formfield_callback=None,
    # widgets=None, validate_max=False, localized_fields=None,
    # labels=None, help_texts=None, error_messages=None,
    # min_num=None, validate_min=False, field_classes=None
)

core/views.py
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView
from .forms import QuestionForm, AlternativeInlineFormset
from .models import Question


class QuestionCreateView(CreateView):
    form_class = QuestionForm
    model = Question
    template_name = "core/index.html"
    success_url = reverse_lazy("question_create_view")

    def get_context_data(self, **kwargs):
        context = super(QuestionCreateView, self).get_context_data(**kwargs)
        context['alternative_formset'] = AlternativeInlineFormset()
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        alternative_formset = AlternativeInlineFormset(self.request.POST)
        if form.is_valid() and alternative_formset.is_valid():
            return self.form_valid(form, alternative_formset)
        else:
            return self.form_invalid(form, alternative_formset)

    def form_valid(self, form, alternative_formset):
        self.object = form.save(commit=False)
        self.object.save()
        
        instance = alternative_formset.save(commit=False)

        for alternative in instance:
            alternative.question = self.object
            alternative.save()
            
        return redirect(reverse("question_create_view"))

    def form_invalid(self, form, alternative_formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                alternative_formset=alternative_formset
            )
        )


class QuestionListView(ListView):
    pass

core/templates/core/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    

</head>

<body>
    <form method="POST" action=".">
        {% csrf_token %}

        <div class="card m-2 rounded shadow mb-3">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5>Questão</h5>
                <button class="btn btn-primary" type="submit">
                    <i class="fa-solid fa-floppy-disk"></i>
                </button>
            </div>
            <div class="card-body">


                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="id_title" name="title" placeholder="Era uma vez ...">
                    <label for="id_title">Título</label>
                </div>

                <div class="form-floating">
                    <textarea name="description" rows="4" id="id_description" class="form-control"
                        placeholder="Era uma vez ..."></textarea>
                    <label for="id_description">Descrição</label>
                </div>



            </div>
        </div>

        <div class="card m-2 rounded shadow">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="mb-0">Alternativas</h5> <button id="add-alternative" class="btn btn-primary" type="button">
                    <i class="fa-solid fa-plus"></i>
                </button>
            </div>

            <div class="card-body" id="alternative-box">
                {{ alternative_formset.non_form_errors }}
                {{ alternative_formset.management_form }}

            </div>
        </div>
    </form>

    <script src="https://kit.fontawesome.com/cf79ec03f6.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script src="{% static 'core/index.js' %}"></script>
</body>

</html>